export const STORAGE_KEYS = {
  ativo: 'ativo',
  tempoPratica: 'tempoPratica',
  historico: 'historico',
  pandaXp: 'pandaXp',
  pandaLevel: 'pandaLevel',
  pandaAchievements: 'pandaAchievements',
  pandaDailyStreak: 'pandaDailyStreak',
  pandaLastTrainingDate: 'pandaLastTrainingDate',
  pandaLastMistakes: 'pandaLastMistakes',
  pandaKeysBestScore: 'pandaKeysBestScore',
  pandaDailyMissions: 'pandaDailyMissions',
  pandaMissionDate: 'pandaMissionDate',
  pandaLessonProgress: 'pandaLessonProgress',
  pandaTrainingRecommendations: 'pandaTrainingRecommendations',
  pandaSelectedLessonId: 'pandaSelectedLessonId',
  pandaSelectedTrainingMode: 'pandaSelectedTrainingMode',
  pandaSealBestScore: 'pandaSealBestScore',
  pandaStartedLessons: 'pandaStartedLessons',
  pandaXpAwards: 'pandaXpAwards',
  pandaCursorMode: 'pandaCursorMode',
} as const;

export type StorageKey = (typeof STORAGE_KEYS)[keyof typeof STORAGE_KEYS];

export const KEYS = {
  historico: STORAGE_KEYS.historico,
  xp: STORAGE_KEYS.pandaXp,
  level: STORAGE_KEYS.pandaLevel,
  achievements: STORAGE_KEYS.pandaAchievements,
  dailyStreak: STORAGE_KEYS.pandaDailyStreak,
  lastTrainingDate: STORAGE_KEYS.pandaLastTrainingDate,
  lastMistakes: STORAGE_KEYS.pandaLastMistakes,
  gameBestScore: STORAGE_KEYS.pandaKeysBestScore,
  tempoPratica: STORAGE_KEYS.tempoPratica,
  tema: STORAGE_KEYS.ativo,
  dailyMissions: STORAGE_KEYS.pandaDailyMissions,
  missionDate: STORAGE_KEYS.pandaMissionDate,
  lessonProgress: STORAGE_KEYS.pandaLessonProgress,
  recommendations: STORAGE_KEYS.pandaTrainingRecommendations,
  selectedLessonId: STORAGE_KEYS.pandaSelectedLessonId,
  selectedTrainingMode: STORAGE_KEYS.pandaSelectedTrainingMode,
  sealBestScore: STORAGE_KEYS.pandaSealBestScore,
  startedLessons: STORAGE_KEYS.pandaStartedLessons,
  xpAwards: STORAGE_KEYS.pandaXpAwards,
  cursorMode: STORAGE_KEYS.pandaCursorMode,
} as const;
