export const STORAGE_KEYS = {
  ativo: 'ativo',
  tempoPratica: 'tempoPratica',
  historico: 'historico',
  pandaXp: 'pandaXp',
  pandaLevel: 'pandaLevel',
  pandaAchievements: 'pandaAchievements',
  pandaDailyStreak: 'pandaDailyStreak',
  pandaLastTrainingDate: 'pandaLastTrainingDate',
  pandaLastMistakes: 'pandaLastMistakes',
  pandaKeysBestScore: 'pandaKeysBestScore',
  pandaDailyMissions: 'pandaDailyMissions',
  pandaMissionDate: 'pandaMissionDate',
  pandaLessonProgress: 'pandaLessonProgress',
  pandaTrainingRecommendations: 'pandaTrainingRecommendations',
  pandaSelectedLessonId: 'pandaSelectedLessonId',
  pandaSelectedTrainingMode: 'pandaSelectedTrainingMode',
  pandaSelectedPracticeTextId: 'pandaSelectedPracticeTextId',
  pandaSelectedPracticeTextTitle: 'pandaSelectedPracticeTextTitle',
  pandaSelectedPracticeText: 'pandaSelectedPracticeText',
  pandaSelectedDailyChallengeId: 'pandaSelectedDailyChallengeId',
  pandaDailyChallengeResult: 'pandaDailyChallengeResult',
  pandaDailyChallengeDate: 'pandaDailyChallengeDate',
  pandaDailyChallengeDismissedDate: 'pandaDailyChallengeDismissedDate',
  pandaRecentRandomWords: 'pandaRecentRandomWords',
  pandaSealBestScore: 'pandaSealBestScore',
  pandaStartedLessons: 'pandaStartedLessons',
  pandaXpAwards: 'pandaXpAwards',
  pandaCursorMode: 'pandaCursorMode',
  pandaKeyboardVisible: 'pandaKeyboardVisible',
  pandaSoundsEnabled: 'pandaSoundsEnabled',
  pandaAnimationsEnabled: 'pandaAnimationsEnabled',
  pandaReducedEffects: 'pandaReducedEffects',
  pandaCloudSyncImported: 'pandaCloudSyncImported',
} as const;

export type StorageKey = (typeof STORAGE_KEYS)[keyof typeof STORAGE_KEYS];

export const KEYS = {
  historico: STORAGE_KEYS.historico,
  xp: STORAGE_KEYS.pandaXp,
  level: STORAGE_KEYS.pandaLevel,
  achievements: STORAGE_KEYS.pandaAchievements,
  dailyStreak: STORAGE_KEYS.pandaDailyStreak,
  lastTrainingDate: STORAGE_KEYS.pandaLastTrainingDate,
  lastMistakes: STORAGE_KEYS.pandaLastMistakes,
  gameBestScore: STORAGE_KEYS.pandaKeysBestScore,
  tempoPratica: STORAGE_KEYS.tempoPratica,
  tema: STORAGE_KEYS.ativo,
  dailyMissions: STORAGE_KEYS.pandaDailyMissions,
  missionDate: STORAGE_KEYS.pandaMissionDate,
  lessonProgress: STORAGE_KEYS.pandaLessonProgress,
  recommendations: STORAGE_KEYS.pandaTrainingRecommendations,
  selectedLessonId: STORAGE_KEYS.pandaSelectedLessonId,
  selectedTrainingMode: STORAGE_KEYS.pandaSelectedTrainingMode,
  selectedPracticeTextId: STORAGE_KEYS.pandaSelectedPracticeTextId,
  selectedPracticeTextTitle: STORAGE_KEYS.pandaSelectedPracticeTextTitle,
  selectedPracticeText: STORAGE_KEYS.pandaSelectedPracticeText,
  selectedDailyChallengeId: STORAGE_KEYS.pandaSelectedDailyChallengeId,
  dailyChallengeResult: STORAGE_KEYS.pandaDailyChallengeResult,
  dailyChallengeDate: STORAGE_KEYS.pandaDailyChallengeDate,
  dailyChallengeDismissedDate: STORAGE_KEYS.pandaDailyChallengeDismissedDate,
  recentRandomWords: STORAGE_KEYS.pandaRecentRandomWords,
  sealBestScore: STORAGE_KEYS.pandaSealBestScore,
  startedLessons: STORAGE_KEYS.pandaStartedLessons,
  xpAwards: STORAGE_KEYS.pandaXpAwards,
  cursorMode: STORAGE_KEYS.pandaCursorMode,
  keyboardVisible: STORAGE_KEYS.pandaKeyboardVisible,
  soundsEnabled: STORAGE_KEYS.pandaSoundsEnabled,
  animationsEnabled: STORAGE_KEYS.pandaAnimationsEnabled,
  reducedEffects: STORAGE_KEYS.pandaReducedEffects,
  cloudSyncImported: STORAGE_KEYS.pandaCloudSyncImported,
} as const;
